# Generated by Django 5.2.5 on 2025-08-14 10:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی پروژه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای پروژه',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مهارت')),
                ('level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تسلط')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مهارت برجسته')),
                ('icon_class', models.CharField(blank=True, help_text='مثلاً: fab fa-python', max_length=100, verbose_name='کلاس آیکن (FontAwesome)')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='skill_icons/', verbose_name='آیکن تصویری')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام تکنولوژی')),
                ('icon', models.CharField(blank=True, help_text='کلاس FontAwesome مثل: fab fa-python', max_length=50, verbose_name='آیکون')),
                ('color', models.CharField(blank=True, help_text='مثلاً: #3776AB', max_length=7, verbose_name='رنگ')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='tech_icons/', verbose_name='آیکون تصویری')),
            ],
            options={
                'verbose_name': 'تکنولوژی',
                'verbose_name_plural': 'تکنولوژی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان شغلی')),
                ('bio', models.TextField(verbose_name='بیوگرافی')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='تصویر پروفایل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='محل زندگی')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/', verbose_name='فایل رزومه')),
                ('social_links', models.JSONField(blank=True, default=dict, null=True)),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیح کوتاه')),
                ('featured_image', models.ImageField(upload_to='projects/', verbose_name='تصویر اصلی')),
                ('github_url', models.URLField(blank=True, verbose_name='لینک گیت\u200cهاب')),
                ('demo_url', models.URLField(blank=True, verbose_name='لینک دمو')),
                ('status', models.CharField(choices=[('completed', 'تکمیل شده'), ('in_progress', 'در حال انجام'), ('on_hold', 'متوقف شده')], default='completed', max_length=20)),
                ('is_featured', models.BooleanField(default=False, verbose_name='پروژه برجسته')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projectcategory')),
                ('technologies', models.ManyToManyField(related_name='projects', to='core.technology', verbose_name='تکنولوژی\u200cها')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
            options={
                'verbose_name': 'تصویر پروژه',
                'verbose_name_plural': 'تصاویر پروژه',
                'ordering': ['order'],
            },
        ),
    ]
